select * from customer limit 20;

--total revenue generated by male vs female customers

select "Gender", SUM(purchase_amount) as revenue 
from customer 
group by "Gender";

--which customer use discount but still spend more than the average purchase amount 

select Customer ID, purchase_amount
from customer
where "Discount Applied" = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer)

--top 5 products with the highest average review rating

select "Item Purchased", ROUND(AVG("Review Rating"::numeric), 2)
from customer
group by "Item Purchased"
order by AVG("Review Rating") desc
limit 5;


--compare average purchase amount between standard and edxpress shipping

select "Shipping Type",
ROUND(AVG(purchase_amount),2)
from customer
where "Shipping Type" in ('Standard','Express')
group by "Shipping Type"


--do subscribed customer spend more? Compare average spend and total revenue between subscribers and non-subscribers.

select "Subscription Status",
COUNT("Customer ID") as total_customers, 
ROUND(AVG(purchase_amount), 2) as avg_spend,
ROUND(SUM(purchase_amount), 2) as total_revenue
from customer
group by "Subscription Status" 
order by total_revenue desc, avg_spend desc;


--which 5 products have the highest percentage of purchase with discount applied?

select "Item Purchased",
ROUND(SUM(CASE WHEN "Discount Applied" = 'Yes' THEN 1 ELSE 0 END)/COUNT(*) * 100,2) as discount_rate
from customer
group by "Item Purchased"
order by discount_rate desc
limit 5;

--Segment customers into new, retuning, and loyal based on their total number of previous purchased
--and show count of each segment

with customer_type as (
select "Customer ID", "Previous Purchases", 
CASE
WHEN "Previous Purchases" = 1 THEN 'New'  
WHEN "Previous Purchases" BETWEEN 2 AND 10 THEN 'Returning' 
ELSE 'Loyal'
END AS customer_segment
from customer
)
select customer_segment, count(*) as "Number of Customers"
from customer_type
group by customer_segment;


--top 3 most purchased products within each category?

with item_counts as (
select "Category",
"Item Purchased",
COUNT("Customer ID") as total_orders,
ROW_NUMBER() over(partition by "Category" order by count("Customer ID")DESC) as item_rank
from customer
group by "Category", "Item Purchased"
)
select item_rank, "Category", "Item Purchased", total_orders
from item_counts
where item_rank <= 3;

--are customers who are repeat buyers (more than previous 5 purchases) also likely to subscribe?

select "Subscription Status",
count("Customer ID") as repeat_buyers
from customer
where "Previous Purchases" > 5
group by "Subscription Status"

--what is revenue contribution of each age group?

select age_group,
SUM("purchase_amount") as total_revenue
from customer
group by age_group
order by total_revenue desc;